### ISSUE TITLE
ClassCastException when starting RequestLogImpl

### ISSUE THREAD

**Issue by peterhalicky** [qos-ch/logback-access#22]
I'm trying to use logback-access with embedded Jetty which I initialize programmatically -- but RequestLogImpl fails when it is started (logs an error and then doesn't log anything).

Easy to reproduce with this code:
```java
RequestLogImpl logbackAccess = new RequestLogImpl();
logbackAccess.setFileName("logback-access.xml");
logbackAccess.start();
```

This will log the following error:
```
java.lang.ClassCastException: class ch.qos.logback.access.jetty.RequestLogImpl cannot be cast to class ch.qos.logback.classic.LoggerContext (ch.qos.logback.access.jetty.RequestLogImpl and ch.qos.logback.classic.LoggerContext are in unnamed module of loader 'app')
	at ch.qos.logback.classic.pattern.EnsureExceptionHandling.process(EnsureExceptionHandling.java:48)
	at ch.qos.logback.core.pattern.PatternLayoutBase.start(PatternLayoutBase.java:87)
	at ch.qos.logback.classic.encoder.PatternLayoutEncoder.start(PatternLayoutEncoder.java:28)
	at ch.qos.logback.core.model.processor.ImplicitModelHandler.postHandleComplex(ImplicitModelHandler.java:207)
	at ch.qos.logback.core.model.processor.ImplicitModelHandler.postHandle(ImplicitModelHandler.java:186)
	at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:257)
	at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:253)
	at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:253)
	at ch.qos.logback.core.model.processor.DefaultProcessor.traversalLoop(DefaultProcessor.java:90)
	at ch.qos.logback.core.model.processor.DefaultProcessor.process(DefaultProcessor.java:106)
	at ch.qos.logback.core.joran.GenericXMLConfigurator.processModel(GenericXMLConfigurator.java:222)
	at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:178)
	at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:123)
	at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:66)
	at ch.qos.logback.access.jetty.RequestLogImpl.runJoranOnFile(RequestLogImpl.java:338)
	at ch.qos.logback.access.jetty.RequestLogImpl.configure(RequestLogImpl.java:292)
	at ch.qos.logback.access.jetty.RequestLogImpl.start(RequestLogImpl.java:278)
	at xyz.inphinity.logbackAccessBug.Main.main(Main.java:9)
```

I get the same with ch.qos.logback.access:jetty11 and ch.qos.logback.access:jetty12; both version 2.0.3.

For sake of completeness this is the config file I use:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration>

<configuration scan="true" scanPeriod="10s">
    <import class="ch.qos.logback.classic.encoder.PatternLayoutEncoder"/>
    <import class="ch.qos.logback.core.ConsoleAppender"/>

    <appender name="STDOUT" class="ConsoleAppender">
        <encoder class="PatternLayoutEncoder">
            <pattern>%h %l %u [%t] "%r" %s %b "%i{Referer}" "%i{User-Agent}"</pattern>
        </encoder>
    </appender>

    <appender-ref ref="STDOUT"/>
</configuration>
```

**Comment by peterhalicky** [comment]
Never mind. I used `PatternLayoutEncoder` from logback, not logback-access.

**Comment by ceki** [comment]
Yes, I was going to reply pointing out the use of `PatternLayoutEncoder` from logback-classic and not logback-access.
